#!/usr/bin/env bash
# Turn a finished `avo run` on a bench target into S9b's evidence, and check the two acceptance
# criteria S9a proved were reachable — now earned by an agent rather than by a script.
#
#   bench/verify-run.sh <target-repo> [run-id] [--target fuzzysearch] [--out <file>]
#
# It reads only what the loop already wrote (the run manifest and the committed lineage), then adds
# the two things a manifest cannot claim about itself: every recorded score re-measured from its own
# commit, and `bench/init.sh --verify` — because if `f` was edited, the curve means nothing.
set -uo pipefail

root="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"

die() { printf 'bench/verify-run.sh: %s\n' "$*" >&2; exit 2; }

target=fuzzysearch
dest=""
run_id=""
out=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --target) [[ -n "${2-}" ]] || die "--target needs a value"; target="$2"; shift 2 ;;
    --out) [[ -n "${2-}" ]] || die "--out needs a value"; out="$2"; shift 2 ;;
    -h|--help) sed -n '2,10p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'; exit 0 ;;
    -*) die "unknown option '$1'" ;;
    *)
      if [[ -z "$dest" ]]; then dest="$1"
      elif [[ -z "$run_id" ]]; then run_id="$1"
      else die "too many positional arguments (got '$1')"; fi
      shift ;;
  esac
done

[[ -n "$dest" ]] || die "need a target repo"
dest="$(cd -- "$dest" 2>/dev/null && pwd)" || die "no such directory"
[[ -d "$dest/.avo" ]] || die "$dest is not an avocode repo (no .avo/)"
command -v jq >/dev/null || die "jq is required"

# Newest run unless one was named. Run ids are timestamps, so lexical order is chronological.
if [[ -z "$run_id" ]]; then
  run_id="$(find "$dest/.avo/runs" -mindepth 1 -maxdepth 1 -type d -printf '%f\n' 2>/dev/null | sort | tail -n 1)"
  [[ -n "$run_id" ]] || die "no runs in $dest/.avo/runs"
fi
manifest="$dest/.avo/runs/$run_id/manifest.json"
[[ -f "$manifest" ]] || die "no manifest at $manifest"

out="${out:-$root/evidence/s9b-run.txt}"
mkdir -p "$(dirname "$out")"
: > "$out"

fails=0
say() { printf '%s\n' "$*" | tee -a "$out"; }
ok()  { say "PASS  $*"; }
bad() { say "FAIL  $*"; fails=$((fails + 1)); }

avo() { "$root/bin/avo" "$@"; }
m() { jq -r "$1" "$manifest"; }

say "# S9b — an agent on bench/$target"
say "# run $run_id in $dest"
say "# generated by bench/verify-run.sh; every number below is read back, not retyped"
say ""

# ================================================================ 1. the run
say "## 1. the run"
say "agent          $(m '.agent')  ($(m '.model // "the agent'"'"'s own default"'))"
say "command        $(m '.command')"
say "iterations     $(m '.iterations | length') of $(m '.max_iters') (per-turn timeout $(m '.timeout_s')s)"
say "stopped on     $(m '.stopped')$(s="$(m '.stop_reason // ""')"; [[ -n "$s" ]] && printf ' — %s' "$s")"
say "thresholds     stall $(m '.thresholds.stall'), thrash $(m '.thresholds.thrash')"
started="$(m '.started_at')"; finished="$(m '.finished_at // ""')"
if [[ -n "$finished" ]]; then
  # `fromdate` parses %Y-%m-%dT%H:%M:%SZ only; these stamps carry milliseconds.
  wall="$(jq -rn --arg a "$started" --arg b "$finished" \
    'def t: sub("\\.[0-9]+";"") | fromdate;
     (($b|t) - ($a|t)) as $s | "\(($s / 60) | floor)m \($s % 60 | floor)s"')"
  say "wall-clock     $wall ($started -> $finished)"
else
  bad "the run never finished — manifest has no finished_at"
fi
say "interventions  $(m '.interventions')"
say "tokens         in $(m '.tokens.input'), out $(m '.tokens.output')"
say ""

say "### per iteration"
# shellcheck disable=SC2016  # $agent/$decision/$steer are jq variables, not shell ones
m '.iterations[] |
  (if .agent.error == null then "agent ok" else "agent failed" end) as $agent
  | (if .decision == null then "no decision"
     elif .decision.action == "committed" then "committed v" + (.decision.version|tostring) + " " + (.decision.primary|tostring) + (.decision.unit // "")
     elif (.decision.reason // "") == "" then .decision.action
     else .decision.action + " — " + .decision.reason end) as $decision
  | (if .intervention == null then "-" else "STEERED: " + (.intervention.signal // .intervention.reason // "directive") end) as $steer
  | "  it " + (.iter|tostring) + "  |  " + $agent + "  |  " + $decision + "  |  since_best " + (.supervision.since_best|tostring) + "  |  " + $steer' | tee -a "$out"
say ""

# ================================================================ 2. the curve
say "## 2. the score curve (P_t)"
lineage="$(avo lineage --cwd "$dest" --json 2>/dev/null)"
count="$(jq 'length' <<<"$lineage")"
if [[ "$count" == 0 ]]; then
  bad "the lineage is empty — the agent committed nothing"
else
  # The run's own starting point, scored from its commit — not v1, which is already an improvement.
  base_sha="$(m '.baseline')"
  base_wt="$(mktemp -d)/baseline"
  base=""
  if git -C "$dest" worktree add -q --detach "$base_wt" "$base_sha" 2>/dev/null; then
    base="$(cd "$base_wt" && .avo/score 2>/dev/null | jq -r '.primary // ""')"
    git -C "$dest" worktree remove --force "$base_wt" 2>/dev/null
  fi
  if [[ -n "$base" ]]; then
    say "v0       $base  (the tree the run started from, ${base_sha:0:8})"
  else
    bad "could not score the run's baseline $base_sha"
    base=null
  fi
  say ""
  say "version  primary      vs v0     vs previous   why"
  jq -r --argjson base "${base:-null}" '"" as $_ | . as $v | range(0; length) |
    $v[.] as $cur
    | (if . == 0 then $base else $v[.-1].score.primary end) as $prev
    | "v" + ($cur.version|tostring)
      + "       " + (($cur.score.primary * 1000 | round) / 1000 | tostring) + ($cur.score.unit // "")
      + "   " + (if $base == null then "-" else (($base / $cur.score.primary * 10 | round) / 10 | tostring) + "x" end)
      + "   " + (if $prev == null then "-" else (($prev / $cur.score.primary * 100 | round) / 100 | tostring) + "x" end)
      + "   " + (($cur.why // "") | split("\n")[0][0:64])' <<<"$lineage" | tee -a "$out"
  say ""
  say "per-config:"
  jq -r '.[] | "  v\(.version)  " + ([.score.scores | to_entries[] | "\(.key)=\(.value)"] | join("  "))' \
    <<<"$lineage" | tee -a "$out"
fi
say ""

# ================================================================ 3. criterion 1 — >= 5, monotone
say "## 3. criterion 1 — at least 5 versions, best monotonically non-decreasing"
if (( count >= 5 )); then
  ok "$count committed version(s)"
else
  bad "only $count committed version(s); S9's criterion is >= 5"
fi
# `avo commit` refuses anything that is not an improvement, so the lineage is monotone by
# construction — which is exactly why it is worth checking: a regression here is a harness bug.
regressions="$(jq -r '
  (if (.[0].score.higher_is_better // false) then 1 else -1 end) as $dir
  | [ . as $v | range(1; length) | select( ($v[.].score.primary - $v[.-1].score.primary) * $dir < 0 )
      | "v\($v[.].version) is worse than v\($v[.-1].version) (\($v[.-1].score.primary) -> \($v[.].score.primary))" ]
  | .[]' <<<"$lineage" 2>/dev/null)"
if [[ -z "$regressions" ]]; then
  (( count > 0 )) && ok "best never went backwards across $count version(s)"
else
  while IFS= read -r line; do bad "$line"; done <<<"$regressions"
fi
say ""

# ================================================================ 4. criterion 2 — reproducible
say "## 4. criterion 2 — every committed version reproduces its recorded score"
say "# a score in the lineage is a measurement, not a claim"
scratch="$(mktemp -d)"
trap 'rm -rf "$scratch"; git -C "$dest" worktree prune 2>/dev/null' EXIT
# Not a pipeline: `bad` in a subshell would increment a copy of $fails and every failure here would
# be printed and then silently dropped.
while read -r n sha recorded; do
  [[ -n "$n" ]] || continue
  wt="$scratch/replay-v$n"
  if ! git -C "$dest" worktree add -q --detach "$wt" "$sha" 2>/dev/null; then
    bad "v$n: could not check out $sha"; continue
  fi
  fresh="$(cd "$wt" && .avo/score 2>/dev/null | jq -r '.primary // "null"')"
  git -C "$dest" worktree remove --force "$wt" 2>/dev/null
  if [[ "$fresh" == null || -z "$fresh" ]]; then
    bad "v$n does not score at all from its own commit"; continue
  fi
  drift="$(jq -n --argjson a "$recorded" --argjson b "$fresh" '(($b - $a) / $a * 1000 | round) / 10')"
  abs="${drift#-}"
  # 50% is deliberately loose, as in test/e2e-bench.sh: this checks that the commit CONTAINS the
  # code that earned the score, on a machine that may be doing something else. A gamed or empty
  # version is off by orders of magnitude, not by a scheduler hiccup.
  if awk -v d="$abs" 'BEGIN {exit !(d <= 50)}'; then
    ok "v$n: recorded ${recorded}ms, fresh ${fresh}ms (${drift}%)"
  else
    bad "v$n: recorded ${recorded}ms but re-scores at ${fresh}ms (${drift}%)"
  fi
done < <(jq -r '.[] | "\(.version) \(.sha) \(.score.primary)"' <<<"$lineage")
say ""

# ================================================================ 5. was f still f?
say "## 5. f is intact"
say "# the in-repo hash gate can be defeated by an agent that edits the gate too (#38); this is the"
say "# audit from outside the target that cannot be reached from inside it"
verify_out="$("$root/bench/init.sh" --verify "$dest" --target "$target" 2>&1)"
verify_rc=$?
printf '%s\n' "$verify_out" | sed 's/^/  /' | tee -a "$out" >/dev/null
printf '%s\n' "$verify_out" | sed 's/^/  /'
if (( verify_rc == 0 )); then ok "bench/init.sh --verify clean"; else bad "f drifted — the curve above means nothing"; fi
say ""

# ================================================================ 6. verdict
say "## 6. verdict"
if (( fails == 0 )); then
  say "all checks passed ($(grep -c '^PASS' "$out") of them)"
else
  say "$fails check(s) FAILED"
fi
exit $(( fails > 0 ))
